/**
 * Amendment to #300: retaining daily_log history (removing the DELETE in
 * _syncRollingSchedule) turned getRollingWindow()'s unbounded
 * `SELECT * FROM daily_log ORDER BY date ASC` into a real regression —
 * every screen that calls it now gets the entire history, forever, instead
 * of just the 7-day rolling window it used to return as a side effect of
 * the (now-removed) prune.
 *
 * getRollingWindow() must be bounded to [today - DAYS_HISTORY, today +
 * DAYS_AHEAD] — the same window _syncRollingSchedule() generates/expects —
 * so callers (e.g. OverviewScreen) keep seeing exactly what they always
 * have, with no caller-side change required.
 *
 * Uses the same sql.js-backed adapter and fresh-module-per-test pattern as
 * syncRollingSchedule.test.ts (see that file / testHelpers/sqljsExpoAdapter.ts
 * for why database.ts's module-level singleton requires this).
 *
 * Issue #300
 */

import { addDays, todayKey } from '../../utils/dates';
import { createSqljsDb } from '../testHelpers/sqljsExpoAdapter';

type DatabaseModule = typeof import('../database');

function loadFreshDatabaseModule(): DatabaseModule {
  jest.resetModules();
  jest.doMock('expo-sqlite', () => ({
    openDatabaseAsync: async () => createSqljsDb(),
    deleteDatabaseAsync: async () => {},
    SQLiteDatabase: class {},
  }));
  // eslint-disable-next-line @typescript-eslint/no-var-requires
  return require('../database') as DatabaseModule;
}

async function insertBareLogRow(
  db: DatabaseModule,
  date: string
): Promise<void> {
  const rawDb = db.getDatabase();
  await rawDb.runAsync(
    'INSERT INTO daily_log (date, walking_task, hammer_task) VALUES (?, ?, ?)',
    [date, 'Walk 10k', 'Bench 3x8']
  );
}

describe('getRollingWindow() stays bounded to the rolling window (#300)', () => {
  afterEach(() => {
    jest.dontMock('expo-sqlite');
  });

  it('excludes far-past history but includes both window boundaries and today', async () => {
    const db = loadFreshDatabaseModule();
    await db.initDatabase(); // seeds daily_log rows today..today+7 from weekly_template

    const today = todayKey();
    const farPast = addDays(today, -400);
    // Lower window boundary (today - DAYS_HISTORY=7). Sync only ever
    // generates rows forward from today, so this has to be inserted by
    // hand to prove the boundary is inclusive.
    const windowStart = addDays(today, -7);
    // Upper window boundary (today + DAYS_AHEAD=7) — already generated by
    // the sync inside initDatabase(), included here for clarity.
    const windowEnd = addDays(today, 7);

    await insertBareLogRow(db, farPast);
    await insertBareLogRow(db, windowStart);

    await db.syncRollingSchedule();

    const rows = await db.getRollingWindow();
    const dates = rows.map((r) => r.date);

    expect(dates).not.toContain(farPast);
    expect(dates).toContain(windowStart);
    expect(dates).toContain(today);
    expect(dates).toContain(windowEnd);
  });
});
